# 12.2 넘파이처럼 텐서플로 사용하기

In [2]:
import tensorflow as tf

## 12.2.1 텐서와 연산

### tf.constant() 함수로 텐서 만들기

In [3]:
tf.constant([[1., 2., 3.], [4., 5., 6.]])

<tf.Tensor: id=0, shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [4]:
tf.constant(42)

<tf.Tensor: id=1, shape=(), dtype=int32, numpy=42>

### 텐서의 크기(shape)와 데이터 타입(dtype)

In [5]:
t = tf.constant([[1., 2., 3.], [4., 5., 6.]])

In [6]:
t.shape

TensorShape([2, 3])

In [7]:
t.dtype

tf.float32

### 인덱스 참조

In [8]:
t[:, 1:]

<tf.Tensor: id=6, shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [10]:
t[..., 1, tf.newaxis]

<tf.Tensor: id=10, shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

### 텐서 연산

In [14]:
t + 10  # tf.add(t, 10)과 동일

<tf.Tensor: id=18, shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [12]:
tf.square(t)

<tf.Tensor: id=13, shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [13]:
t @ tf.transpose(t)  # tf.matmul() 함수와 동일

<tf.Tensor: id=16, shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

### 12.2.2 텐서와 넘파이

In [15]:
import numpy as np

In [16]:
a = np.array([2., 4., 5.])

In [17]:
tf.constant(a)

<tf.Tensor: id=19, shape=(3,), dtype=float64, numpy=array([2., 4., 5.])>

In [18]:
t.numpy()  # = np.array(t)

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [23]:
tf.square(a)

<tf.Tensor: id=23, shape=(3,), dtype=float64, numpy=array([ 4., 16., 25.])>

In [27]:
np.square(t)

array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)

### 12.2.3 타입 변환

타입 변환은 성능을 크게 감소시킬 수 있기 때문에, 텐서플로는 어떤 타입 변환도 자동으로 수행하지 않는다.

In [28]:
tf.constant(2.) + tf.constant(40)  # 실수텐서와 정수텐서는 더할 수 없다

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2] name: add/

In [29]:
tf.constant(2.) + tf.constant(40., dtype=tf.float64)  # 32비트 실수와 64비트 실수도 더할 수 없다

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a double tensor [Op:AddV2] name: add/

In [30]:
t2 = tf.constant(40., dtype=tf.float64)

In [31]:
tf.constant(2.0) + tf.cast(t2, tf.float32)

<tf.Tensor: id=31, shape=(), dtype=float32, numpy=42.0>

### 12.2.4 변수

앞선 tf.Tensor는 변경이 불가능한 객체이다. 변경 가능한 변수를 만드는 방법은 아래와 같다.

In [32]:
v = tf.Variable([[1., 2., 3.], [4., 5., 6.]])

In [33]:
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [35]:
v.assign(2 * v)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [36]:
v[0, 1].assign(42)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2., 42.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [37]:
v[:, 2].assign([0., 1.])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2., 42.,  0.],
       [ 8., 10.,  1.]], dtype=float32)>

In [38]:
v.scatter_nd_update(indices=[[0, 0], [1, 2]], updates=[100., 200.])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[100.,  42.,   0.],
       [  8.,  10., 200.]], dtype=float32)>